FROM debian:9
RUN apt-get update && apt-get install -y \
    git
RUN apt-get install -y \
    --no-install-recommends \
    build-essential \
    autoconf \ 
    libtool \ 
    libssl-dev \
    libpcre3-dev \
    asciidoc \
    xmlto \
    zlib1g-dev

RUN mkdir -p /shadowsocks/
WORKDIR /shadowsocks
RUN git clone https://github.com/wangw469/shadowsocksr-libev.git
WORKDIR shadowsocksr-libev
RUN ./configure && make
RUN make install

RUN apt-get install -y \
    --no-install-recommends \
    curl
